### ISSUE TITLE
species codes

### ISSUE THREAD

**Issue by kaycole** [USFWS/AMAPPS#4]
There are duplicate species codes for 

1) unidentified common or roseate tern
2) unidentified pinnipeds

Check to see if both are used in the database, chose one, correct codes and update species list.

**Comment by thoufer** [comment]
Unidentified Common Tern or Roseate Tern.. This could go a couple of ways..
We have classified common terns as "medium terns" and roseate terns as
"large terns" and there are unidentified for each grouping (UNMT, UNLT,
respectively).  If an observer is unable to distinguish medium/large, the
observation would (should) default to simply unidentified Tern  (UNTE).

Unidentified pinniped should translate to unidentified seal (SEAL)

Hope that helps figure out which is the correct code..

---------------------------------------
US Fish and Wildlife Service
Division of Migratory Bird Management
11510 American Holly Dr.
Laurel MD 20708

301-497-5869 (phone)
301-497-5871 (fax)

**Comment by kaycole** [comment]
unidentified pinnipeds (UNPI, UNPD) have been removed from the species list and 1 record of UNPI in the observation table has been changed to UNSE (unidentified seal)

For unidentified common/roseate tern, CRTE has been removed, and 5 records in the observation table have been changed to UCRT. I'm leaving the codes for size classes of unidentified terns for now but yes, maybe we should just list those all as unidentified terns in the long run.
